#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: emily pecoraro

# Short bio or description (displayed in the header)
description: undergraduate student at bucknell university

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://lh3.googleusercontent.com/7UblWvLT4c0_l5C5ExAgbDWZ1UDT4EAQEtYE88o-jGVMlekNRAFO7q5mnGtlH3akk1kXMb65K6Xj48xYR2rhvUm6sU6XIUGvS2cXk53suySVeXajZ6nbx04_cWhuZrULzj8JSwIsHPhMAQhUYyReJSNEGKASIygq48RlT6Y6eNzl9mkSoOOn4srLtRQWMb8UcFMvbz-_zzUxigp5g3yQCi4uaptrY3Lr4hXPsIpRo1Mn8nRDXGqMeGKWbaZ4OeQuF6af8s72D7hRWBl52_Baoq00kZ44VfClDh2GPCz48Xvp6PW_3db2RYTnzL4I-Foim_Jk2ZoUtHAbixiR9dRvyBohcyLI55EXrC6Yv7gpnmiaQaoluns_3m9UM9bC8tbi3q4G-Q93mTXNf2BlKk6asY3wiiWDqpyNlKUosP3UVORDiy3nco_78H-FNv7n6HR6yqtDQ8Xwlnni64NQofv1zg4m8wLtPJ42Y2rTLL0AAI3aAHg5Kp0vK1fkS67BT3kfSvaVIpV2gBg7CNuKfgWkd5WC0_-8KNWdRhqtisWVjXoAJG0YgIfmzMJ3X5WBFE4shq6SzADyGNc1C0VETOE-aLtAM9fVjPz7HqiJ-iHZCnjFYDskZIvd68Uw2rYN9U7BW-E-EqhC48GyovbmROaIaY8jh5S7mxisH8j8X5aAJ5OE0FU1_8UToQd5sIA7Rbs=w826-h997-no?authuser=1 #
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
 
  email: eip003@bucknell.edu

  github: emilypecoraro
  instagram: emilypec

  #twitter: (note :make a twitter)


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
#disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
#google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
#url:

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
